[package]
name = "cusp"
version = "1.0.1"
edition = "2024"
license = "MIT or Apache-2.0"
authors = ["SubAt0mic"]
description = "A Concurrent, Lock-Free cell with atomic operations."
keywords = ["lock-free", "rcu", "atomic", "cell", "concurrent"]
categories = ["concurrency"]

[dependencies]
seize = "0.5.1"
fastrand = { version = "2.5.0" }
