[package]
name = "single_flight"
version = "0.0.1"
edition = "2024"

[dependencies]
event-listener = "5.4.1"
fastrand = "2.5.0"
papaya = "0.2.4"
pin-project-lite = "0.2.17"
concurrent_cell = { path = "../concurrent_cell" }
simple_defer = { path = "../simple_defer" }
conquer-util = { version = "0.3.0", features = ["random", "back-off"] }

[dev-dependencies]
futures = "0.3.33"
tokio = { version = "1.53.1", features = ["full"] }
